### ISSUE TITLE
AWS EC2 Dynamic Folder script does not specify aws command output format

### ISSUE THREAD

**Issue by ambish** [royalapplications/toolbox#12]
If a user has pre-configured the output format for the 'aws' command within their config file to anything other than JSON, the script fails with the error (taken from Royal TSX on OS X):

An error occurred while executing the dynamic folder's script: Traceback (most recent call last):
  File "/Users/<username>/Library/Caches/com.lemonmojo.RoyalTSX.App/DynF_b258321f-a40a-45ca-9f0b-dc030bcbb786_1563215081", line 80, in <module>
    print(get_instances("us-east-2"))
  File "/Users/<username>/Library/Caches/com.lemonmojo.RoyalTSX.App/DynF_b258321f-a40a-45ca-9f0b-dc030bcbb786_1563215081", line 15, in get_instances
    response = json.loads(response_json)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This can be avoided by explicitly specifying the output format in the dynamic folder script as part of the 'cmd' variable as follows:

**cmd = "aws ec2 describe-instances --output json"**

**Comment by eightnoneone** [comment]
Good point. Easy fix, I’ll change and submit.

**Comment by lemonmojo** [comment]
Just implemented this in https://github.com/royalapplications/toolbox/commit/7021de9577e09162f48d2352e82b869f73df1619. Thx for the suggestion, @ambish!
